### PR TITLE
Fix for index skip on successive cutscenes

### LINKED ISSUE #171: Next index doesn't update properly when starting a cutscene from a cutscene
> When a cutscene is started while another one is running, the next step index is not reset properly, which can lead to one or more steps being skipped.
Please consider the example item below. It contains a CS which starts another CS in its step 3. I would expect that the second CS runs through entirely (i.e. 1 -> 2 -> 3), instead it shows only step 1 and step 3.

Export code to test:
> !nxvutjomq4Fo3l3PTPIk8gcCZXnArDlG39qOL2viJHwMMGOV0F73UPkoic(WDpCdLnjB)YMVS73csFzKm0NE8eczOqcEN5f4he0mO50Fg87gYWacb0pKTMumh5Dax1LTD6s4do27SJfEvX(bToXRLFdY)fsaqn(iA(w08YeTMw)b(UAGecPVWEIZiMAwjCrB(062xg6XlHooYytkTaZibVeIyRJCy9DIMPYKqMkrxmBIdUeskNzQF97VPvXM6GzDFa6rRmw5RFGFWSGgVSF9yxyZ5eDhraE3e7RIblUKMqihiNkHExtwlNC3dsrvC0CYro(KLyHZ3ALwxfBlvZMHLeW6TiEFmd2xmd4yQmVgoEwEbf9hvg1unHCkMMSYGVfAgkLImsy8GTZUBFM0np6xUQH9ffH4)efX6IYhUxxSEIDEIDsof4YjLRYnhuEykwLNnrLnXG673sFaF)oUOfEQFZ)snHyJMOkoSWQsjFZlwtLfUEVwztNJzvX3xwSWHXw4kGQflqs9Ar9ZeShulxQYN9Afv8zYlXwYRTLcUGHzFTk(5IvKyRi)lmtqKPuTayVjZprbU5ydoGU5Tkyp69pTetTCcykop5rvrzRQFUt30UUeBCj2fL4aOiMDnqvj)ZpvcdbjPd74yAyBA2kRPgFeAOKsFlUWjFO3Ft7AHXf8IHHSDuBwccDULx0LJQWJI)n941x3MTJD2oUimU3wk2I8Hg8F5VE5VxLAgAtuAtTmDpnRbnPNpUzLA8e09mBeXYJcoQXrbhUb2o6L)tz3w5gETeN7ehaMZSHs(eBg0NtqWTsG6ZH(0WtN4Ytan0DOlnF14xsFgmDvPY(8L0HRzrixhJQHxNuH200uTk9H6(jlA2Ob7ZjHWtE7QyLY)a

### PR DESCRIPTION
**Pull request by Solanya**
Fixes #171 
Will need additional tests to make sure nothing else behaves incorrectly when calling cutscenes successively.

### CODE REVIEW

File: totalRP3_Extended/dialogues/dialogues.lua [hunk 1]
```diff
@@ -243,11 +245,13 @@ local function playDialogStep()
 				-- End point
 				dialogFrame.Chat.NextButton:SetScript("OnClick", finishDialog);
 			else
+				print(dialogFrame.stepIndex)
```
Comment (Meorawr) [inline totalRP3_Extended/dialogues/dialogues.lua:248]: bruh

Comment (Solanya) [reply totalRP3_Extended/dialogues/dialogues.lua:248]: see, i said it needed additional tests :)

File: totalRP3_Extended/dialogues/dialogues.lua [hunk 2]
```diff
@@ -301,7 +304,7 @@ local function setModel(model, dialogStepClass, field)
 end
 
 -- Prepare all the texts for a step
-function processDialogStep()
+function processDialogStep(isNewDialog)
```
Comment (Meorawr) [inline totalRP3_Extended/dialogues/dialogues.lua:307]: Is this new parameter actually having a value passed in from somewhere else that isn't visible from this set of changes alone, or is it going to be perpetually nil?
